### PR TITLE
Patch 1 - Adding Nife Labs to the LF Edge Landscape

### PR DESCRIPTION
**Pull request by nida**
Adding Nife Labs to the landscape

### CODE REVIEW

**Comment by ninjaginja** [comment]
Hello @nida, it looks like you may be experiencing some trouble with the .svg format of your logo file. Here are some helpful instructions to get the image in the correct format - https://github.com/cncf/landscapeapp/blob/master/README.md#logos

**Comment by nida** [comment]
> Hello @nida, it looks like you may be experiencing some trouble with the .svg format of your logo file. Here are some helpful instructions to get the image in the correct format - https://github.com/cncf/landscapeapp/blob/master/README.md#logos

I think I will create a new SVG from scratch. that way will not go through this issue.

**Comment by nida** [comment]
Added Nife to the landscape

**Comment by nida** [comment]
LGTM

**Comment by nida** [comment]
LGTM

**Comment by nida** [comment]
@ninjaginja do I need to do anything else?  I have reviewed the landscape on https://deploy-preview-416--lfedge.netlify.app

**Comment by ninjaginja** [comment]
Apologies @nida, I missed the latest updates here.

**Pull request merged**
