### PR TITLE
Add KubeOne to the Landscape

### PR DESCRIPTION
**Pull request by xmulligan**

### CODE REVIEW

**Comment by wesreisz** [comment]
@xmulligan Do you have an svg of this logo?  We only use svg in the landscape for space.
https://github.com/kubermatic/kubeone/blob/master/docs/img/kubeone-logo-text.png

**Comment by xmulligan** [comment]
@wesreisz  just added the svg

**Comment by wesreisz** [comment]
@xmulligan sorry for the delay. There were some changes happening. I had issues with this PR, so I pulled it and merged it under a different one. https://github.com/State-of-the-Edge/lfedge-landscape/pull/320

**Comment by xmulligan** [comment]
Perfect, thanks so much!

**Pull request closed without merging**
