### PR TITLE
Update Kubermatic Product logos

### PR DESCRIPTION
**Pull request by KrissiWi**

### CODE REVIEW

**Comment by ninjaginja** [comment]
@KrissiWi We typically restrict organizations/projects to a single listing within the landscape. I see that you've updated the KubeOne logo to the Kubermatic logo, which makes it appear as a duplicate listing within the landscape and can lead to confusion. Of the two, is there a preferred listing that you'd like to see represented?

**Comment by KrissiWi** [comment]
@ninjaginja : Sorry for the very belated reply. We would prefer the Kubermatic Kubernetes Platform to be represented. Thanks!

**Comment by KrissiWi** [comment]
@ninjaginja : Hi there, I just quickly wanted to check if there are any updates on this?

**Comment by ninjaginja** [comment]
apologies for the delay @KrissiWi . I removed the KubeOne listing and merged this PR.

**Pull request merged**
