### PR TITLE
Correct name is Tanzu Kubernetes Grid, not Tanzu Grid 

### PR DESCRIPTION
**Pull request by wesreisz**
Fixed the name of the platform

### CODE REVIEW

**Comment by ninjaginja** [comment]
@wesreisz  this pr seems to be introducing changes to the processed_landscape.yml file, resulting in the removal of repo links for many of the listings. Was this intended?

**Comment by wesreisz** [comment]
> @wesreisz this pr seems to be introducing changes to the processed_landscape.yml file, resulting in the removal of repo links for many of the listings. Was this intended?

It's likely derived from a change to the landscape app and will occur whenever the next full build happens on the server. Looks like the last server build was two days ago? I pulled from master, branched, and only changed the text of the TKG. Before I pushed, I ran a full local build to validate nothing was breaking and committed the changes (which is where those updates to process_landscape came from). I just reran the local server and I see VyOS still has a repo (attaching a screenshot for reference). I'm guessing it's pulled from a different source now? It might be worth pinging Dan or one of the others to see where. 

Screen_Shot_2020-07-01_at_9_13_19_AM

**Comment by dankohn** [comment]
I suspect you have an out-of-date local version of landscapeapp. I fixed the branch with:
```
git checkout tkg
git checkout master processed_landscape.yml
yf
git commit -sam 'Recreate processed_landscape.yml'
```

Please update your local dev environment with the directions from https://github.com/cncf/landscapeapp#installing-locally to have landscapeapp in a singling directory of lfedge-landscape and enter `a` to ensure things are up-to-date.

**Comment by wesreisz** [comment]
@ninjaginja Sounds like this is safe to merge.

**Pull request merged**
